CREATE TYPE "ban_scopes" AS ENUM('IP_ADDRESS', 'USER', 'ANON', 'FAILED_CREDENTIAL', 'ARCHIVED_USER', 'ARCHIVED_ANON');--> statement-breakpoint
CREATE TABLE "activities" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"timestamp" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid,
	"users_archive_id" bigint,
	"label" text NOT NULL,
	"success" boolean NOT NULL,
	"failure_cause" text,
	"meta" jsonb,
	"failed_credential" varchar(255),
	"anon_id" uuid,
	"anons_archive_id" bigint,
	"ip_address" inet NOT NULL,
	"weight" smallint DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "activities_archive" (
	"id" uuid NOT NULL,
	"timestamp" timestamp with time zone NOT NULL,
	"archive_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "activities_archive_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"user_id" uuid,
	"users_archive_id" bigint,
	"label" text NOT NULL,
	"success" boolean NOT NULL,
	"failure_cause" text,
	"meta" jsonb,
	"failed_credential" varchar(255),
	"anon_id" uuid,
	"anons_archive_id" bigint,
	"ip_address" inet NOT NULL,
	"weight" smallint NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anons" (
	"id" uuid PRIMARY KEY,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"token_created_at" timestamp with time zone NOT NULL,
	"ip_addresses" inet[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anons_archive" (
	"id" uuid NOT NULL,
	"created_at" timestamp with time zone,
	"updated_at" timestamp with time zone,
	"archive_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "anons_archive_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"token_created_at" timestamp with time zone NOT NULL,
	"ip_addresses" inet[] NOT NULL,
	"user_id" uuid,
	"users_archive_id" bigint
);
--> statement-breakpoint
CREATE TABLE "bans" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"scope" "ban_scopes" NOT NULL,
	"ip_address" inet,
	"failed_credential" varchar(255),
	"activity_ids" uuid[] NOT NULL,
	"activities_archive_ids" bigint[] NOT NULL,
	"anon_id" uuid,
	"anons_archive_id" bigint,
	"user_id" uuid,
	"users_archive_id" bigint,
	"total_weight" bigint DEFAULT 0 NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() + '10 minutes',
	CONSTRAINT "bans_scope_target_unique" UNIQUE NULLS NOT DISTINCT("scope","ip_address","failed_credential","user_id","anon_id","users_archive_id","anons_archive_id"),
	CONSTRAINT "bans_single_target_check" CHECK (num_nonnulls("ip_address", "failed_credential", "user_id", "anon_id", "users_archive_id", "anons_archive_id") = 1)
);
--> statement-breakpoint
CREATE TABLE "bans_archive" (
	"id" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"archive_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "bans_archive_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"scope" "ban_scopes" NOT NULL,
	"ip_address" inet,
	"failed_credential" varchar(255),
	"activity_ids" uuid[] NOT NULL,
	"activities_archive_ids" bigint[] NOT NULL,
	"anon_id" uuid,
	"anons_archive_id" bigint,
	"user_id" uuid,
	"users_archive_id" bigint,
	"total_weight" bigint DEFAULT 0 NOT NULL,
	"expires_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "email_verifications" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"anon_id" uuid,
	"user_id" uuid,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"email" varchar(254) NOT NULL,
	"passcode_hash" text NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() + '15 minutes' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "email_verifications_archive" (
	"id" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"archive_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "email_verifications_archive_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"anon_id" uuid,
	"user_id" uuid,
	"attempts" smallint DEFAULT 0 NOT NULL,
	"email" varchar(254) NOT NULL,
	"anons_archive_id" bigint,
	"users_archive_id" bigint,
	"verified_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_addresses" inet[] NOT NULL,
	"refresh_generation" smallint DEFAULT 0 NOT NULL,
	"user_id" uuid NOT NULL,
	"nonce_hash" text NOT NULL,
	"expires_at" timestamp with time zone DEFAULT now() + '30 days' NOT NULL,
	"grace_expires_at" timestamp with time zone,
	"grace_token" text,
	"revoked_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "sessions_archive" (
	"id" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"archive_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_archive_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"ip_addresses" inet[] NOT NULL,
	"refresh_generation" smallint DEFAULT 0 NOT NULL,
	"user_id" uuid,
	"users_archive_id" bigint,
	"expires_at" timestamp with time zone NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" varchar(254) NOT NULL,
	"password_hash" text
);
--> statement-breakpoint
CREATE TABLE "users_archive" (
	"id" uuid NOT NULL,
	"created_at" timestamp with time zone NOT NULL,
	"updated_at" timestamp with time zone NOT NULL,
	"archive_id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_archive_archive_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"archived_at" timestamp with time zone DEFAULT now() NOT NULL,
	"email" varchar(254)
);
--> statement-breakpoint
CREATE INDEX "activities_timestamp_index" ON "activities" ("timestamp");--> statement-breakpoint
CREATE INDEX "activities_ip_address_timestamp_index" ON "activities" ("ip_address","timestamp");--> statement-breakpoint
CREATE INDEX "activities_failed_credential_timestamp_index" ON "activities" ("failed_credential","timestamp") WHERE "failed_credential" is not null;--> statement-breakpoint
CREATE INDEX "activities_user_id_timestamp_index" ON "activities" ("user_id","timestamp") WHERE "user_id" is not null;--> statement-breakpoint
CREATE INDEX "activities_anon_id_timestamp_index" ON "activities" ("anon_id","timestamp") WHERE "anon_id" is not null;--> statement-breakpoint
CREATE INDEX "activities_users_archive_id_timestamp_index" ON "activities" ("users_archive_id","timestamp") WHERE "users_archive_id" is not null;--> statement-breakpoint
CREATE INDEX "activities_anons_archive_id_timestamp_index" ON "activities" ("anons_archive_id","timestamp") WHERE "anons_archive_id" is not null;--> statement-breakpoint
CREATE INDEX "bans_expires_at_index" ON "bans" ("expires_at");--> statement-breakpoint
CREATE INDEX "bans_activity_ids_index" ON "bans" USING gin ("activity_ids");--> statement-breakpoint
CREATE INDEX "bans_ip_address_index" ON "bans" ("ip_address") WHERE "ip_address" is not null;--> statement-breakpoint
CREATE INDEX "bans_failed_credential_index" ON "bans" ("failed_credential") WHERE "failed_credential" is not null;--> statement-breakpoint
CREATE INDEX "bans_user_id_index" ON "bans" ("user_id") WHERE "user_id" is not null;--> statement-breakpoint
CREATE INDEX "bans_anon_id_index" ON "bans" ("anon_id") WHERE "anon_id" is not null;--> statement-breakpoint
CREATE INDEX "bans_users_archive_id_index" ON "bans" ("users_archive_id") WHERE "users_archive_id" is not null;--> statement-breakpoint
CREATE INDEX "bans_anons_archive_id_index" ON "bans" ("anons_archive_id") WHERE "anons_archive_id" is not null;--> statement-breakpoint
CREATE UNIQUE INDEX "email_verifications_email_lower_anon_unique" ON "email_verifications" (lower("email"),"anon_id");--> statement-breakpoint
CREATE UNIQUE INDEX "email_verifications_email_lower_user_unique" ON "email_verifications" (lower("email"),"user_id");--> statement-breakpoint
CREATE UNIQUE INDEX "users_email_lower_unique" ON "users" (lower("email"));--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_users_archive_id_users_archive_archive_id_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_anon_id_anons_id_fkey" FOREIGN KEY ("anon_id") REFERENCES "anons"("id");--> statement-breakpoint
ALTER TABLE "activities" ADD CONSTRAINT "activities_anons_archive_id_anons_archive_archive_id_fkey" FOREIGN KEY ("anons_archive_id") REFERENCES "anons_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "activities_archive" ADD CONSTRAINT "activities_archive_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "activities_archive" ADD CONSTRAINT "activities_archive_UlPtyivnITiJ_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "activities_archive" ADD CONSTRAINT "activities_archive_anon_id_anons_id_fkey" FOREIGN KEY ("anon_id") REFERENCES "anons"("id");--> statement-breakpoint
ALTER TABLE "activities_archive" ADD CONSTRAINT "activities_archive_HTD6HTU05M1J_fkey" FOREIGN KEY ("anons_archive_id") REFERENCES "anons_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "anons_archive" ADD CONSTRAINT "anons_archive_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "anons_archive" ADD CONSTRAINT "anons_archive_users_archive_id_users_archive_archive_id_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_anon_id_anons_id_fkey" FOREIGN KEY ("anon_id") REFERENCES "anons"("id");--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_anons_archive_id_anons_archive_archive_id_fkey" FOREIGN KEY ("anons_archive_id") REFERENCES "anons_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "bans" ADD CONSTRAINT "bans_users_archive_id_users_archive_archive_id_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "bans_archive" ADD CONSTRAINT "bans_archive_anon_id_anons_id_fkey" FOREIGN KEY ("anon_id") REFERENCES "anons"("id");--> statement-breakpoint
ALTER TABLE "bans_archive" ADD CONSTRAINT "bans_archive_anons_archive_id_anons_archive_archive_id_fkey" FOREIGN KEY ("anons_archive_id") REFERENCES "anons_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "bans_archive" ADD CONSTRAINT "bans_archive_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "bans_archive" ADD CONSTRAINT "bans_archive_users_archive_id_users_archive_archive_id_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "email_verifications" ADD CONSTRAINT "email_verifications_anon_id_anons_id_fkey" FOREIGN KEY ("anon_id") REFERENCES "anons"("id");--> statement-breakpoint
ALTER TABLE "email_verifications" ADD CONSTRAINT "email_verifications_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "email_verifications_archive" ADD CONSTRAINT "email_verifications_archive_anon_id_anons_id_fkey" FOREIGN KEY ("anon_id") REFERENCES "anons"("id");--> statement-breakpoint
ALTER TABLE "email_verifications_archive" ADD CONSTRAINT "email_verifications_archive_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "email_verifications_archive" ADD CONSTRAINT "email_verifications_archive_a2JFgnYaZisD_fkey" FOREIGN KEY ("anons_archive_id") REFERENCES "anons_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "email_verifications_archive" ADD CONSTRAINT "email_verifications_archive_f5LjnxHR4TRD_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "sessions_archive" ADD CONSTRAINT "sessions_archive_user_id_users_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id");--> statement-breakpoint
ALTER TABLE "sessions_archive" ADD CONSTRAINT "sessions_archive_users_archive_id_users_archive_archive_id_fkey" FOREIGN KEY ("users_archive_id") REFERENCES "users_archive"("archive_id");