export const PENALTY_INTERVAL_INITIAL_QTY = 10
export const PENALTY_INTERVAL_MAX_QTY = 120
export const PENALTY_INTERVAL_UNIT = 'minutes'
export const PENALTY_INTERVAL_INITIAL = `${PENALTY_INTERVAL_INITIAL_QTY} ${PENALTY_INTERVAL_UNIT}`
