/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAnonRouteRouteImport } from './routes/_auth-anon/route'
import { Route as AuthDynamicRouteRouteImport } from './routes/_auth-dynamic/route'
import { Route as AuthGatewayRouteRouteImport } from './routes/_auth-gateway/route'
import { Route as AuthProtectedRouteRouteImport } from './routes/_auth-protected/route'
import { Route as AuthAnonLandingPageRouteImport } from './routes/_auth-anon/landing-page'
import { Route as AuthDynamicIndexRouteImport } from './routes/_auth-dynamic/index'
import { Route as AuthGatewaySignInRouteImport } from './routes/_auth-gateway/sign-in'
import { Route as AuthGatewaySignUpRouteImport } from './routes/_auth-gateway/sign-up'
import { Route as AuthProtectedSettingsRouteRouteImport } from './routes/_auth-protected/settings/route'

const AuthAnonRouteRoute = AuthAnonRouteRouteImport.update({
  id: '/_auth-anon',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDynamicRouteRoute = AuthDynamicRouteRouteImport.update({
  id: '/_auth-dynamic',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGatewayRouteRoute = AuthGatewayRouteRouteImport.update({
  id: '/_auth-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProtectedRouteRoute = AuthProtectedRouteRouteImport.update({
  id: '/_auth-protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAnonLandingPageRoute = AuthAnonLandingPageRouteImport.update({
  id: '/landing-page',
  path: '/landing-page',
  getParentRoute: () => AuthAnonRouteRoute,
} as any)
const AuthDynamicIndexRoute = AuthDynamicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDynamicRouteRoute,
} as any)
const AuthGatewaySignInRoute = AuthGatewaySignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthGatewayRouteRoute,
} as any)
const AuthGatewaySignUpRoute = AuthGatewaySignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthGatewayRouteRoute,
} as any)
const AuthProtectedSettingsRouteRoute =
  AuthProtectedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthDynamicIndexRoute
  '/settings': typeof AuthProtectedSettingsRouteRoute
  '/landing-page': typeof AuthAnonLandingPageRoute
  '/sign-in': typeof AuthGatewaySignInRoute
  '/sign-up': typeof AuthGatewaySignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthDynamicIndexRoute
  '/settings': typeof AuthProtectedSettingsRouteRoute
  '/landing-page': typeof AuthAnonLandingPageRoute
  '/sign-in': typeof AuthGatewaySignInRoute
  '/sign-up': typeof AuthGatewaySignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth-anon': typeof AuthAnonRouteRouteWithChildren
  '/_auth-dynamic': typeof AuthDynamicRouteRouteWithChildren
  '/_auth-gateway': typeof AuthGatewayRouteRouteWithChildren
  '/_auth-protected': typeof AuthProtectedRouteRouteWithChildren
  '/_auth-protected/settings': typeof AuthProtectedSettingsRouteRoute
  '/_auth-anon/landing-page': typeof AuthAnonLandingPageRoute
  '/_auth-gateway/sign-in': typeof AuthGatewaySignInRoute
  '/_auth-gateway/sign-up': typeof AuthGatewaySignUpRoute
  '/_auth-dynamic/': typeof AuthDynamicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/settings' | '/landing-page' | '/sign-in' | '/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/settings' | '/landing-page' | '/sign-in' | '/sign-up'
  id:
    | '__root__'
    | '/_auth-anon'
    | '/_auth-dynamic'
    | '/_auth-gateway'
    | '/_auth-protected'
    | '/_auth-protected/settings'
    | '/_auth-anon/landing-page'
    | '/_auth-gateway/sign-in'
    | '/_auth-gateway/sign-up'
    | '/_auth-dynamic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthAnonRouteRoute: typeof AuthAnonRouteRouteWithChildren
  AuthDynamicRouteRoute: typeof AuthDynamicRouteRouteWithChildren
  AuthGatewayRouteRoute: typeof AuthGatewayRouteRouteWithChildren
  AuthProtectedRouteRoute: typeof AuthProtectedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-anon': {
      id: '/_auth-anon'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthAnonRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-dynamic': {
      id: '/_auth-dynamic'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthDynamicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-gateway': {
      id: '/_auth-gateway'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthGatewayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-protected': {
      id: '/_auth-protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth-anon/landing-page': {
      id: '/_auth-anon/landing-page'
      path: '/landing-page'
      fullPath: '/landing-page'
      preLoaderRoute: typeof AuthAnonLandingPageRouteImport
      parentRoute: typeof AuthAnonRouteRoute
    }
    '/_auth-dynamic/': {
      id: '/_auth-dynamic/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthDynamicIndexRouteImport
      parentRoute: typeof AuthDynamicRouteRoute
    }
    '/_auth-gateway/sign-in': {
      id: '/_auth-gateway/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthGatewaySignInRouteImport
      parentRoute: typeof AuthGatewayRouteRoute
    }
    '/_auth-gateway/sign-up': {
      id: '/_auth-gateway/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthGatewaySignUpRouteImport
      parentRoute: typeof AuthGatewayRouteRoute
    }
    '/_auth-protected/settings': {
      id: '/_auth-protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthProtectedSettingsRouteRouteImport
      parentRoute: typeof AuthProtectedRouteRoute
    }
  }
}

interface AuthAnonRouteRouteChildren {
  AuthAnonLandingPageRoute: typeof AuthAnonLandingPageRoute
}

const AuthAnonRouteRouteChildren: AuthAnonRouteRouteChildren = {
  AuthAnonLandingPageRoute: AuthAnonLandingPageRoute,
}

const AuthAnonRouteRouteWithChildren = AuthAnonRouteRoute._addFileChildren(
  AuthAnonRouteRouteChildren,
)

interface AuthDynamicRouteRouteChildren {
  AuthDynamicIndexRoute: typeof AuthDynamicIndexRoute
}

const AuthDynamicRouteRouteChildren: AuthDynamicRouteRouteChildren = {
  AuthDynamicIndexRoute: AuthDynamicIndexRoute,
}

const AuthDynamicRouteRouteWithChildren =
  AuthDynamicRouteRoute._addFileChildren(AuthDynamicRouteRouteChildren)

interface AuthGatewayRouteRouteChildren {
  AuthGatewaySignInRoute: typeof AuthGatewaySignInRoute
  AuthGatewaySignUpRoute: typeof AuthGatewaySignUpRoute
}

const AuthGatewayRouteRouteChildren: AuthGatewayRouteRouteChildren = {
  AuthGatewaySignInRoute: AuthGatewaySignInRoute,
  AuthGatewaySignUpRoute: AuthGatewaySignUpRoute,
}

const AuthGatewayRouteRouteWithChildren =
  AuthGatewayRouteRoute._addFileChildren(AuthGatewayRouteRouteChildren)

interface AuthProtectedRouteRouteChildren {
  AuthProtectedSettingsRouteRoute: typeof AuthProtectedSettingsRouteRoute
}

const AuthProtectedRouteRouteChildren: AuthProtectedRouteRouteChildren = {
  AuthProtectedSettingsRouteRoute: AuthProtectedSettingsRouteRoute,
}

const AuthProtectedRouteRouteWithChildren =
  AuthProtectedRouteRoute._addFileChildren(AuthProtectedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthAnonRouteRoute: AuthAnonRouteRouteWithChildren,
  AuthDynamicRouteRoute: AuthDynamicRouteRouteWithChildren,
  AuthGatewayRouteRoute: AuthGatewayRouteRouteWithChildren,
  AuthProtectedRouteRoute: AuthProtectedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
